import Head from 'next/head'
import Image from 'next/image'
import { Hero } from '../index'
import Saber from '../../public/images/profile/Saber.png'
import { TypeAnimation } from 'react-type-animation';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&family=Kanit:ital,wght@1,500&family=Lato:ital,wght@1,900&family=Noto+Sans+Mahajani&family=Rubik:ital,wght@1,700&family=Ubuntu:ital,wght@1,700&display=swap" rel="stylesheet" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <div className='w-full h-full inline-block z-0 bg-light p-8 lg:p-32 pt-0'>
          <div className='flex items-center justify-between  w-full'>
            <div className='w-full lg:w-2/3'>
              <h2 className='text-3xl leading-7 tracking-tight lg:text-5xl'>Hello 👋🏾, I'm Saber</h2>
              <p className="font-extrabold opacity-60 text-3xl pt-3 leading-6 tracking-tighter font-mono no-underline sm:text-2xl md:text-3xl lg:text-4xl text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
                <TypeAnimation
                  sequence={[
                    'A Passionate Full Stack Web3 Engineer',
                    1000,
                    'A Community Manager',
                    1000,
                    'A Listening Manager',
                    1000,
                  ]}
                  wrapper="span"
                  speed={50}
                  style={{ display: 'inline-block' }}
                  repeat={Infinity}
                />
              </p>
              <p className='w-full text-2xl font-semibold opacity-80 '>
                I'm a highly motivated Full Stack Web3 Engineer with a deep passion for crafting innovative and efficient solutions. My expertise lies in building robust applications that leverage the latest web technologies, ensuring a seamless and interactive user experience. I thrive on challenges and am dedicated to staying at the forefront of emerging trends in the ever-evolving world of web development.
              </p>
            </div>
            <div className=' lg:block w-1/2 ml-8'> 
              <Image src={Saber} alt='Saber' className='w-full h-full' />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
