import Head from 'next/head'
import Image from 'next/image'
import { Hero } from '../index'
import Saber from '../../public/images/profile/Saber.png'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <div className='w-full h-full inline-block z-0 bg-light p-32 pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div>
              <h2 className='tezxt-3xl leading-7 tracking-tight'>Hello 👋🏾, I'm Saber </h2>
              <p></p>
            </div>
            <div>
              <Image src={Saber} alt='Saber' className='w-full h-full' />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
